services:
  redis-movie:
    image: redis:latest
    container_name: redis-movie
    ports:
      - "7777:6379"

  test-redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "1234:6379"
