services:
  movie:
    container_name: movie-app
    build:
      context: .
    depends_on:
      - redis-movie
    ports:
      - "8000:8000"

  redis-movie:
    image: redis:latest
    container_name: redis-movie
    ports:
      - "7777:6379"

  test-redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "1234:6379"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  prometheus_data:
