name: Python Checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - "movie-app/**"

jobs:
  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: './python-version'

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

      - name: Test with black
        run: black ./
