name: Python Checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - "movie-app/**"

jobs:
  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

      - name: Test with black
        run: black --check --diff ./
