name: Python Checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - "movie-app/**"
      - ".github/workflows/**"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

      - name: Test with black
        run: black --check --diff ./

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: 'check'
          version-file: 'pyproject.toml'

      - name: Show dependencies
        run: uv tree

  run-tests:
    runs-on: ubuntu-latest

    needs: run-checks
    steps:

      # установка Python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Установка uv и всех зависимостей
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # pytest
      - name: Run Pytest
        run: uv run pytest
        env:
          testing: 1
          REDIS_PORT: 1234
