name: Python Checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - "movie-app/**"

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder GH Actions step
        run: echo "Hello World!"
