name: Python Checks

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - "movie-app/**"
      - ".github/workflows/**"

jobs:

  list_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Show dependencies
        run: uv tree

  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

      - name: Test with black
        run: black --check --diff ./
